### ISSUE TITLE
Android crushes

### ISSUE THREAD

**Issue by Partysun** [oney/react-native-webrtc#111]
Hi, I have the problem with new 0.10 version on Android devices. When I try pc.addLocalStream(), app crashes.
It's a very stable bug. If I downgrade version to 0.8, Android addLocalStream is ok.

```
08-07 13:34:08.943 11697 11748 I org.webrtc.Logging: WebRtcAudioManager: Sample rate is set to 48000 Hz
08-07 13:34:08.955 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: canUseAcousticEchoCanceler: true
08-07 13:34:08.960 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: canUseAutomaticGainControl: false
08-07 13:34:08.968 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: canUseNoiseSuppressor: true
08-07 13:34:08.970 11697 11748 D JVM     : JNIEnvironment::RegisterNatives(org/webrtc/voiceengine/WebRtcAudioRecord)
08-07 13:34:08.971 11697 11748 I org.webrtc.Logging: WebRtcAudioRecord: ctor@[name=Thread-7248, id=7248]
08-07 13:34:08.971 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: ctor@[name=Thread-7248, id=7248]
08-07 13:34:08.971 11697 11748 I org.webrtc.Logging: WebRtcAudioManager: init@[name=Thread-7248, id=7248]
08-07 13:34:08.972 11697 11748 I org.webrtc.Logging: WebRtcAudioManager: audio mode is: MODE_NORMAL
08-07 13:34:08.973 11697 11748 I org.webrtc.Logging: WebRtcAudioRecord: enableBuiltInAEC(true)
08-07 13:34:08.973 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: setAEC(true)
08-07 13:34:08.973 11697 11748 I org.webrtc.Logging: WebRtcAudioRecord: enableBuiltInNS(true)
08-07 13:34:08.973 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: setNS(true)
08-07 13:34:09.305 11697 11744 I org.webrtc.Logging: PeerConnectionFactory: onNetworkThreadReady
08-07 13:34:09.364 11697 11748 I org.webrtc.Logging: PeerConnectionFactory: onWorkerThreadReady
08-07 13:34:09.478 11697 11749 I org.webrtc.Logging: PeerConnectionFactory: onSignalingThreadReady
08-07 13:34:14.952 11697 11753 D com.oney.WebRTCModule.WebRTCModule: mMediaStreamId: 0
08-07 13:34:19.285 11697 11753 D com.oney.WebRTCModule.WebRTCModule: addStreamtrue
08-07 13:34:19.285 11697 11753 D com.oney.WebRTCModule.WebRTCModule: peerConnectionSetRemoteDescription() start
08-07 13:34:20.187 11697 11753 D com.oney.WebRTCModule.WebRTCModule: peerConnectionSetRemoteDescription() end
08-07 13:34:20.391 11697 11753 D com.oney.WebRTCModule.WebRTCModule: RTCPeerConnectionCreateAnswerWithObjectID start
08-07 13:34:20.392 11697 11753 D com.oney.WebRTCModule.WebRTCModule: RTCPeerConnectionCreateAnswerWithObjectID end
08-07 13:34:20.403 11697 11753 D com.oney.WebRTCModule.WebRTCModule: peerConnectionSetLocalDescription() start
08-07 13:34:20.958 11697 11748 I org.webrtc.Logging: WebRtcAudioRecord: enableBuiltInAEC(false)
08-07 13:34:20.958 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: setAEC(false)
08-07 13:34:20.959 11697 11748 I org.webrtc.Logging: WebRtcAudioRecord: enableBuiltInNS(true)
08-07 13:34:20.959 11697 11748 I org.webrtc.Logging: WebRtcAudioEffects: setNS(true)
08-07 13:34:21.021 11697 11744 I org.webrtc.Logging: NetworkMonitor: Start monitoring from native observer -1424603392
08-07 13:34:21.023 11697 11744 W System.err: 	at org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.getNetworkState(NetworkMonitorAutoDetect.java:191)
08-07 13:34:21.023 11697 11744 W System.err: 	at org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:441)
08-07 13:34:21.023 11697 11744 W System.err: 	at org.webrtc.NetworkMonitor.setAutoDetectConnectivityStateInternal(NetworkMonitor.java:139)
08-07 13:34:21.023 11697 11744 W System.err: 	at org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)
08-07 13:34:21.023 11697 11744 E rtc     :
08-07 13:34:21.023 11697 11744 E rtc     :
08-07 13:34:21.023 11697 11744 E rtc     : #
08-07 13:34:21.023 11697 11744 E rtc     : # Fatal error in ../../webrtc/api/java/jni/androidnetworkmonitor_jni.cc, line 195
08-07 13:34:21.023 11697 11744 E rtc     : # last system error: 88
08-07 13:34:21.023 11697 11744 E rtc     : # Check failed: !jni()->ExceptionCheck()
08-07 13:34:21.023 11697 11744 E rtc     : # Error during CallVoidMethod
08-07 13:34:21.023 11697 11744 E rtc     : #
```

**Comment by zxcpoiu** [comment]
sorry, I can't reproduce it by myself.
have you figured out how to solve it yet?

**Comment by Partysun** [comment]
No, I am using 0.8 now.

**Comment by zxcpoiu** [comment]
@Partysun please try #123 to see if it works.

**Comment by txthinking** [comment]
0.11.0 too

**Comment by zxcpoiu** [comment]
can you try latest 0.12.0 on master branch? it contains webrtc 53 versions

**Comment by txthinking** [comment]
Reproduce:
0. Let Nexus 5X(android 6.0) fuck Mac Book
1. Create a new RN project with `react-native: 0.31.0` and `react-native-webrtc: 0.11.0`
2. Follow the react-native-webrtc android install guide.
3. `$ react-native run-android`. I do not write any js code about react-native-webrtc

A moment, build apk ok but can not be run.

@zxcpoiu You can't reproduce, so this only occur on Nexus 5X?
@Partysun What phone are you using?

**Comment by zxcpoiu** [comment]
@txthinking 

1. are you using `0.11.0` or `0.12.0`?
2. I didn't see `pc.addLocalStream()` in https://github.com/oney/react-native-webrtc/blob/master/RTCPeerConnection.js
how you trigger this error?

**Comment by txthinking** [comment]
1. I am using 0.11.0
2. I didn't see this error. Just crash like the reproduce steps i write. No any js  code about react-native-webrtc.

**Comment by davidperrenoud** [comment]
As Nexus 5X is a 64-bit phone, could https://github.com/oney/react-native-webrtc/pull/131 be related?

**Comment by zxcpoiu** [comment]
@davidperrenoud nice catch!
@txthinking could you try applying patch discussed in #131?

**Comment by txthinking** [comment]
master: `git://github.com/oney/react-native-webrtc.git#9a747f5f23176ccd76c481a899cd681fb67ac003`

` $ react-native run-android`
```
...
error: error reading /Users/tx/go/src/app/node_modules/react-native-webrtc/android/libs/libjingle_peerconnection.so.jar; error in opening zip file
error: error reading /Users/tx/go/src/app/node_modules/react-native-webrtc/android/libs/libjingle_peerconnection.so.jar; error in opening zip file
Note: /Users/tx/go/src/app/node_modules/react-native-webrtc/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
...
error: error reading /Users/tx/go/src/app/android/app/build/intermediates/exploded-aar/law/WebRTCModule/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in open
ing zip file
error: error reading /Users/tx/go/src/app/android/app/build/intermediates/exploded-aar/law/WebRTCModule/unspecified/jars/libs/libjingle_peerconnection.so.jar; error in open
ing zip file
...
:app:preDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDexDebug'.
> java.lang.RuntimeException: Exception while checking library jar
...
```

**Comment by davidperrenoud** [comment]
@txthinking Did you install `git lfs` and use `git clone`? Check that `libjingle_peerconnection.so.jar` is a >1 Mb file. https://github.com/oney/react-native-webrtc#installation

**Comment by zxcpoiu** [comment]
thanks @davidperrenoud 

I have updated master for android:

1. disable git lfs
2. remove 64 bit .so in libjingle

@txthinking could you try again?

**Comment by txthinking** [comment]
Built success, but occur java error `couldn't find key mandatory in dynamic object` when run.
> I think you should get a 64bit phone for testing

**Comment by haovn577** [comment]
The same here, "couldn't find key mandatory in dynamic object" 
Device: Samsung Note 3 (Android 5.0)

**Comment by zxcpoiu** [comment]
Even on 0.13.0?

**Comment by davidperrenoud** [comment]
@haovn577 Try something like this in `getUserMedia`:
```
audio: true,
video: {
  facingMode: isFront ? 'user' : 'environment',
  optional: [],
  mandatory: { minWidth: 800, minHeight: 600 },
  width: { min: 800, ideal: 1280 },
  height: { min: 600, ideal: 1024 }
}
```

**Comment by txthinking** [comment]
@davidperrenoud  it works. But why?

**Comment by txthinking** [comment]
But has another crash. 0.13.0
```
pc.createOffer
.....

WHEN:
c.onsignalingstatechange => ''have-local-offer"
CRASH
````
And this code can run well on 0.8.0

**Comment by haovn577** [comment]
@txthinking 
Add this permission line: <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by haovn577** [comment]
@davidperrenoud  thanks!
But now can't remote video ( Web <-> Android)

`
09-23 19:24:30.349 20020-20509/com.rctwebrtcdemo E/ACodec: onConfigureComponent mime.c_str() = video/x-vnd.on2.vp8
09-23 19:24:30.349 20020-20509/com.rctwebrtcdemo E/ACodec: [OMX.qcom.video.encoder.vp8] storeMetaDataInBuffers (output) failed w/ err -2147483648
...
09-23 19:24:45.419 20020-20070/com.rctwebrtcdemo I/ReactNativeJS: 'oniceconnectionstatechange', 'failed'
`

**Comment by haovn577** [comment]
it works on Nexus 5.

**Comment by txthinking** [comment]
@haovn577 Which line?
Now you can connect with other video? (web <-> android)

**Comment by haovn577** [comment]
@txthinking Add to your AndroidManifest.xml
Yes,  tested with 3 peers, 2 android devices and 1 browser.

**Comment by txthinking** [comment]
ping @zxcpoiu. Fixed issue.

**Comment by zxcpoiu** [comment]
wow, nice folks!
