### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by snsekar** [oney/react-native-webrtc#159]
Hi,
I am getting following error and App crashed : Android 4.2.2

```
E/AndroidRuntime(19059): FATAL EXCEPTION: main
E/AndroidRuntime(19059): java.lang.NoSuchMethodError: com.oney.WebRTCModule.WebRTCView.isInLayout
E/AndroidRuntime(19059): 	at com.oney.WebRTCModule.WebRTCView.requestSurfaceViewRendererLayout(WebRTCView.java:317)
E/AndroidRuntime(19059): 	at com.oney.WebRTCModule.WebRTCView.setScalingType(WebRTCView.java:379)
E/AndroidRuntime(19059): 	at com.oney.WebRTCModule.WebRTCView.<init>(WebRTCView.java:132)
E/AndroidRuntime(19059): 	at com.oney.WebRTCModule.RTCVideoViewManager.createViewInstance(RTCVideoViewManager.java:24)
E/AndroidRuntime(19059): 	at com.oney.WebRTCModule.RTCVideoViewManager.createViewInstance(RTCVideoViewManager.java:10)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:206)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:874)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:847)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/AndroidRuntime(19059): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
E/AndroidRuntime(19059): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:789)
E/AndroidRuntime(19059): 	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
E/AndroidRuntime(19059): 	at android.view.Choreographer.doFrame(Choreographer.java:560)
E/AndroidRuntime(19059): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
E/AndroidRuntime(19059): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime(19059): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(19059): 	at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(19059): 	at android.app.ActivityThread.main(ActivityThread.java:5317)
E/AndroidRuntime(19059): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19059): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19059): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
E/AndroidRuntime(19059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
E/AndroidRuntime(19059): 	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by zxcpoiu** [comment]
#142

**Comment by snsekar** [comment]
@zxcpoiu Thank you so much. That issue resloved.
