### ISSUE TITLE
not working with latest react version (0.37)

### ISSUE THREAD

**Issue by sagivo** [oney/react-native-webrtc#173]
ios - 
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/sagivo/dev/side/react/RCTWebRTCDemo/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/RCTWebRTCDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
(node:58174) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:58174) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RCTWebRTCDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at _runIOS (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/react-native/local-cli/runIOS/runIOS.js:91:34)
    at Promise (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5)
    at tryCallTwo (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/sagivo/dev/side/react/RCTWebRTCDemo/node_modules/react-native/local-cli/cliEntry.js:95:3)
    at Object.<anonymous> (/Users/sagivo/.nvm/versions/node/v7.1.0/lib/node_modules/react-native-cli/index.js:116:7)
```

android - crashing after joining a room

**Comment by zxcpoiu** [comment]
Does #174 solves your issue on iOS?

and on android, do you grant enough permissions? like RECORD_AUDIO

**Comment by sagivo** [comment]
I think my mistake was not following the installation details from the webRTC repo. We should mention it as a step for install in the readme. I'll try again but closing the issue for now. Thanks!

**Comment by zxcpoiu** [comment]
ok, thanks for improve docs @sagivo
