### ISSUE TITLE
[Android] Can't work on  Samsung tablet(6.0.1)

### ISSUE THREAD

**Issue by oceantear** [oney/react-native-webrtc#298]
I am new for react-native.
I try to follow doc to build an apk for android. But, it can't work normally on my Samsung tablet
(SM-P580 android 6.0.1).
It show below error on my tablet:
![screenshot_20170615-133122](https://user-images.githubusercontent.com/6262664/27166737-689289bc-51cf-11e7-8dd0-afdc0c38428f.png)

Android Studio show below error:
<pre>
E/unknown:React: Unable to download JS bundle
                                                                  com.facebook.react.devsupport.DebugServerException: The development server returned response error code: 500
                                                                  
                                                                  URL: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false
                                                                  
                                                                  Body:
                                                                  {"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
                                                                      at com.facebook.react.devsupport.DevServerHelper.processBundleResult(DevServerHelper.java:390)
                                                                      at com.facebook.react.devsupport.DevServerHelper.access$400(DevServerHelper.java:65)
                                                                      at com.facebook.react.devsupport.DevServerHelper$5$1.execute(DevServerHelper.java:333)
                                                                      at com.facebook.react.devsupport.MultipartStreamReader.emitChunk(MultipartStreamReader.java:69)
                                                                      at com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:116)
                                                                      at com.facebook.react.devsupport.DevServerHelper$5.onResponse(DevServerHelper.java:321)
                                                                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)
</pre>

Is any one can give me a hint? Thanks in advanced.

**Comment by saghul** [comment]
What do you see in the terminal window that pops up?

**Comment by oceantear** [comment]
After i type `react-native run-android` in terminal, i got below message:
<pre>BUILD SUCCESSFUL

Total time: 25.891 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
Running adb -s 52030d5e43eda359 reverse tcp:8081 tcp:8081
Starting the app on 52030d5e43eda359 (adb -s 52030d5e43eda359 shell am start -n com.rctwebrtcdemo/.MainActivity)...
Starting: Intent { cmp=com.rctwebrtcdemo/.MainActivity VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
</pre>

**Comment by saghul** [comment]
There should be a new terminal window showing up with the react native packager. What's the output on that one?

**Comment by oceantear** [comment]
I didn't find any new terminal windows when I type `react-native run-android` in terminal.
Did I miss some setting before run react compiler?

**Comment by saghul** [comment]
There should be some window where the react-native packager runs. Alternatively, you can check the output of `react-native log-android`.
