### ISSUE TITLE
npm  start  failed  with   RTCPeerConnection.js

### ISSUE THREAD

**Issue by djalmabright** [oney/react-native-webrtc#375]
I  tried   deploy   in  the  Heroku  server   but  throws  this  error  :
 react-native-webrtc@1.58.2 start /app
> babel-node index.js --presets es2015,stage-2

/app/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^
SyntaxError: /app/RTCPeerConnection.js: Unexpected token, expected ; (18:5)
  16 | const {WebRTCModule} = NativeModules;
  17 |
> 18 | type RTCSignalingState =
     |      ^
  19 |   'stable' |
  20 |   'have-local-offer' |
  21 |   'have-remote-offer' | 
   at Parser.pp$5.raise (/app/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/app/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/app/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/app/node_modules/babylon/lib/index
.js:2236:8)
    at Parser.pp$1.parseStatement (/app/node_modules/babylon/lib/index.js:1911:1
7)
    at Parser.pp$1.parseBlockBody (/app/node_modules/babylon/lib/index.js:2268:2
1)
    at Parser.pp$1.parseTopLevel (/app/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/app/node_modules/babylon/lib/index.js:1673:17)
    at parse (/app/node_modules/babylon/lib/index.js:7305:37)
    at File.parse (/app/node_modules/babel-core/lib/transformation/file/index.js
:517:15)

npm ERR! Linux 3.13.0-133-generic
npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
npm ERR! node v6.11.5

**Comment by zxcpoiu** [comment]
I'm not sure what is your use case, but it seems like you should have something like `bable-preset-react-native`

**Comment by zxcpoiu** [comment]
or lt least install all preset that `bable-preset-react-native` is using
