### ISSUE TITLE
[Android] Crash on some devices

### ISSUE THREAD

**Issue by samk17cmutpm** [oney/react-native-webrtc#424]
Hi, I'm facing a very weird crash, It only happens in some japanese device (S8+ Android 7)
Could any one help me, please !
#0. Crashed: Thread-40
at org.webrtc.Logging.getStackTraceString(Logging.java:176)
at org.webrtc.Logging.e(Logging.java:156)
at org.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:383)
at java.lang.Thread.run(Thread.java:762)

--

Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
at org.webrtc.Logging.getStackTraceString(Logging.java:176)
at org.webrtc.Logging.e(Logging.java:156)
at org.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:383)
at java.lang.Thread.run(Thread.java:762)

Caused by java.lang.ClassNotFoundException: Didn't find class "com.google.devtools.build.android.desugar.runtime.ThrowableExtension" on path: DexPathList[[zip file "/data/app/jp.co.neolab.calling-1/base.apk"],nativeLibraryDirectories=[/data/app/jp.co.neolab.calling-1/lib/arm, /data/app/jp.co.neolab.calling-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at org.webrtc.Logging.getStackTraceString(Logging.java:176)
at org.webrtc.Logging.e(Logging.java:156)
at org.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:383)
at java.lang.Thread.run(Thread.java:762)

#0. Crashed: Thread-40
at org.webrtc.Logging.getStackTraceString(Logging.java:176)
at org.webrtc.Logging.e(Logging.java:156)
at org.webrtc.MediaCodecVideoDecoder$1.run(MediaCodecVideoDecoder.java:383)
at java.lang.Thread.run(Thread.java:762)

**Comment by zxcpoiu** [comment]
If this issue is on top of #423 , please merge them into one,also, if possible, provide further details to reproduce.

ex: specific device modal, use case, use codec, how to reproduce...etc. 
I think it's kind of helpless by current info you provided so far. :cry:

**Comment by saghul** [comment]
That was solved with the last M63 upgrade.
