### ISSUE TITLE
The android app crashes on changing orientation of the phone after clicking pic from react-native-camera

### ISSUE THREAD

**Issue by ashisalokhe** [oney/react-native-webrtc#593]
#### Expected behavior

The app should not crash and should allow video calling.

#### Observerd behavior
App crashes on orientation change

** Crashlytics report:

#0. Crashed: main
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:2249)
       at com.google.android.cameraview.Camera1.setDeviceOrientation(Camera1.java:534)
       at com.google.android.cameraview.CameraView$1.onDisplayOrientationChanged(CameraView.java:124)
       at com.google.android.cameraview.DisplayOrientationDetector.dispatchOnDisplayOrientationChanged(DisplayOrientationDetector.java:114)
       at com.google.android.cameraview.DisplayOrientationDetector$1.onOrientationChanged(DisplayOrientationDetector.java:90)
       at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:835)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

--

Fatal Exception: java.lang.RuntimeException: setParameters failed
       at android.hardware.Camera.native_setParameters(Camera.java)
       at android.hardware.Camera.setParameters(Camera.java:2249)
       at com.google.android.cameraview.Camera1.setDeviceOrientation(Camera1.java:534)
       at com.google.android.cameraview.CameraView$1.onDisplayOrientationChanged(CameraView.java:124)
       at com.google.android.cameraview.DisplayOrientationDetector.dispatchOnDisplayOrientationChanged(DisplayOrientationDetector.java:114)
       at com.google.android.cameraview.DisplayOrientationDetector$1.onOrientationChanged(DisplayOrientationDetector.java:90)
       at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:835)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

#### Steps to reproduce the problem
The app and video call works fine when there is no any react-native-camera component involved.
I have implemented react-native-camera to take pictures in the prior component.
And when i start video call after clicking pictures the app crashes on orientation change.

#### Platform information

* **React Native version**: 0.57.8
* **Plugin version**: 1.69.0
* **OS**: Android
* **OS version**: 9

**Comment by ashisalokhe** [comment]
Scenario works fine with DrawerNavigator and Crashes when StackNavigator is used..

**Comment by ashisalokhe** [comment]
Fixed it by resetting navigation as
`  this.props.navigation.reset([NavigationActions.navigate({ routeName: 'Call' })], 0); `
