### ISSUE TITLE
Sometime Crash on Android

### ISSUE THREAD

**Issue by den4kox** [oney/react-native-webrtc#608]
Error log:

#0. Crashed: decoder-texture-thread
       at org.webrtc.HardwareVideoDecoder.onFrame(HardwareVideoDecoder.java:443)
       at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:315)
       at org.webrtc.SurfaceTextureHelper.lambda$returnTextureFrame$4$SurfaceTextureHelper(SurfaceTextureHelper.java:247)
       at org.webrtc.SurfaceTextureHelper$$Lambda$4.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at org.webrtc.HardwareVideoDecoder.onFrame(HardwareVideoDecoder.java:443)
       at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:315)
       at org.webrtc.SurfaceTextureHelper.lambda$returnTextureFrame$4$SurfaceTextureHelper(SurfaceTextureHelper.java:247)
       at org.webrtc.SurfaceTextureHelper$$Lambda$4.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

#### Expected behavior
Sometime crash
#### Observerd behavior
No crash
#### Steps to reproduce the problem
watch stream 5-10 minutes
#### Platform information

* **React Native version**: 0.57.6
* **Plugin version**: 1.69.0
* **OS**: Android
* **OS version**: 7.0
* **Device: Galaxy**: S7 Edge
* **RAM Free**: 26.6%
* **Disk Free**: 47.7%

**Comment by saghul** [comment]
I have also seen this occasionally. It looks like a WebRTC bug. Please report it upstream: https://bugs.chromium.org/p/webrtc/issues/list

**Comment by zxcpoiu** [comment]
seems have been fixed in M75 https://chromium.googlesource.com/external/webrtc/+/a9daea4377287b353a478d82b53e9cdf23726859%5E%21/#F0

**Comment by saghul** [comment]
Nice catch!
